parameters:
    xidea_base.configuration.pool.class: Xidea\Bundle\BaseBundle\ConfigurationPool
    xidea_base.template.configuration.pool.class: Xidea\Bundle\BaseBundle\Template\TemplateConfigurationPool
    xidea_base.template_manager.class: Xidea\Bundle\BaseBundle\Template\TemplateManager
    xidea_base.paginator.class: Xidea\Bundle\BaseBundle\Pagination\Paginator
    xidea_base.sorter.class: Xidea\Bundle\BaseBundle\Pagination\Sorter

services:
    xidea_base.configuration.pool:
        class: %xidea_base.configuration.pool.class%
    xidea_base.template.configuration.pool:
        class: %xidea_base.template.configuration.pool.class%
    xidea_base.template_manager:
        class: %xidea_base.template_manager.class%
        arguments:
            - @xidea_base.template.configuration.pool
            - @templating
    xidea_base.paginator:
        class: %xidea_base.paginator.class%
        calls:
             - [setSorter, [@xidea_base.sorter]]
    xidea_base.sorter:
        class: %xidea_base.sorter.class%