parameters:
    xidea_base.configuration.pool.class: Xidea\Base\Configuration\Pool\DefaultPool
    xidea_base.pagination.request.class: Xidea\Base\Pagination\Request\SymfonyRequest
    xidea_base.paginator.class: Xidea\Base\Pagination\Paginator\DefaultPaginator
    xidea_base.sorter.class: Xidea\Base\Pagination\Sorter\DefaultSorter
    xidea_base.response_handler.class: Xidea\Bundle\BaseBundle\Response\Handler\DefaultHandler

services:
    xidea_base.configuration.pool:
        class: '%xidea_base.configuration.pool.class%'
    xidea_base.pagination.request:
        class: '%xidea_base.pagination.request.class%'
        arguments:
            - '@request_stack'
    xidea_base.paginator:
        class: '%xidea_base.paginator.class%'
        arguments:
            - '@xidea_base.pagination.request'
            - '@xidea_base.sorter'
    xidea_base.sorter:
        class: '%xidea_base.sorter.class%'
        arguments:
            - '@xidea_base.pagination.request'
    xidea_base.response_handler:
        class: '%xidea_base.response_handler.class%'
        arguments:
            - '@xidea_base.routing_manager'
            - '@xidea_base.templating_manager'