parameters:
    xidea_base.templating.configuration.pool.class: Xidea\Bundle\BaseBundle\Templating\Configuration\Pool\DefaultPool
    xidea_base.templating_manager.class: Xidea\Bundle\BaseBundle\Templating\Manager\DefaultManager

services:
    xidea_base.templating.configuration.pool:
        class: '%xidea_base.templating.configuration.pool.class%'
    xidea_base.templating_manager:
        class: '%xidea_base.templating_manager.class%'
        arguments:
            - '@xidea_base.templating.configuration.pool'
            - '@templating'