parameters:
    xidea_base.template.manager.class: Xidea\Bundle\BaseBundle\Template\TemplateManager
    xidea_base.twig.template.extension.class: Xidea\Bundle\BaseBundle\Twig\Extension\TemplateExtension

services:
    xidea_base.template.manager:
        class: %xidea_base.template.manager.class%
        arguments:
            - @xidea_base.configuration.pool
            - @templating
    xidea_base.twig.template.extension:
        class: %xidea_base.twig.template.extension.class%
        arguments:
            - @xidea_base.configuration.pool
        tags:
            - { name: twig.extension }