parameters:
    xidea_base.twig.routing.extension.class: Xidea\Bundle\BaseBundle\Twig\Extension\RoutingExtension
    xidea_base.twig.templating.extension.class: Xidea\Bundle\BaseBundle\Twig\Extension\TemplatingExtension
    xidea_base.twig.pagination.extension.class: Xidea\Bundle\BaseBundle\Twig\Extension\PaginationExtension

services:
    xidea_base.twig.templating.extension:
        class: '%xidea_base.twig.templating.extension.class%'
        arguments:
            - '@xidea_base.templating.configuration.pool'
        tags:
            - { name: twig.extension }
    xidea_base.twig.pagination.extension:
        class: '%xidea_base.twig.pagination.extension.class%'
        arguments:
            - '@xidea_base.templating.configuration.pool'
            - '@router'
        tags:
            - { name: twig.extension }