parameters:
    xidea_base.twig.template.extension.class: Xidea\Bundle\BaseBundle\Twig\Extension\TemplateExtension

services:
    xidea_base.twig.template.extension:
        class: %xidea_base.twig.template.extension.class%
        arguments:
            - @xidea_base.template.configuration.pool
        tags:
            - { name: twig.extension }